### ISSUE TITLE
Could you provide the code of metrics in this work?

### ISSUE THREAD

**Issue by chengyi-chris** [weihui1308/Moire-Backdoor-Attack#1]
Sorry, I wonder how to compute metrics, for example, ASR, PAP in this work.
Can you provide what you can?

**Comment by weihui1308** [comment]
We're glad you're interested in our work.

Our method was experimented on two detectors, YOLOv5 and Faster RCNN, respectively.
In fact, the computational code for ASR is different in the two detector projects. But the formula for calculation is the same:

ASR = 1 - (TP_WithAttack / TP_WithoutAttack).

TP refers to the number of True Positive samples.

For PAP, it refers to the AP value measured on the poisoned dataset. 

The code to calculate AP and TP can be found in official YOLOv5 and Faster RCNN repository. For example, for YOLOv5, it's on line 276 of val.py.
